Add modify user password
biblibre/urungi pull request #331
Opened 2022-09-30 15:07 UTC by ThibaudGLT

Add new route and new modal to allow each user to change their own password

2022-10-12 07:33 UTC, jajm requested changes
Dans l'ensemble ça fonctionne, mais il y a un petit problème: le bouton pour changer de mot de passe s'affiche sur toutes les pages utilisateur, mais ça change le mot de passe de l'utilisateur connecté.
Donc en tant qu'admin, si je vais sur un autre utilisateur et que j'essaye de changer son mot de passe, en fait c'est le mien que je change! :-)
Il faudrait juste cacher le bouton quand on est sur la page d'un autre utilisateur

(il y a aussi d'autres remarques plus bas dans le code)

2022-10-12 07:33 UTC, jajm commented on public/js/users/users-modify-password-modal.component.js
> +            const inputs = document.getElementsByClassName('input-passwd');
Là tu récupères tous les `.input-passwd` de la page (pas seulement de la modale). Il faut éviter d'utiliser ce genre de fonctions dans les composants angularjs.
En plus t'as pas besoin de faire ça: le fait de changer `vm.inputType` suffit

2022-10-12 07:33 UTC, jajm commented on public/js/users/users-modify-password-modal.component.js
> +            vm.user = angular.copy(vm.resolve.user);
Si j'ai bien compris, on n'utilise jamais ce qui vient de `vm.resolve.user`. Les seules propriétés de `vm.user` qu'on utilise viennent du formulaire. Donc à mon avis le composant `appUsersModifyPasswordModal` n'a pas besoin de récupérer un `user` (et pas besoin de le passer dans l'appel à `$uibModal.open`

2022-10-12 07:33 UTC, jajm commented on public/js/users/users-modify-password-modal.component.js
> +                notify.error(gettextCatalog.getString(error));
Je trouve que c'est bizarre d'avoir une erreur dans une notif dans le coin de l'écran, alors que le `alertMessage` s'affiche dans la modale. Deux endroits différents pour un même feedback. Je mettrais tout dans la modale (sauf le message de succès forcément puisque la modale est fermée à ce moment là)

2022-10-12 07:33 UTC, jajm commented on public/js/users/users-view.controller.js
> +                    user: () => vm.currentUser,
Comme dit plus haut, pas besoin de passer `vm.currentUser`

2022-10-12 07:33 UTC, jajm commented on public/js/users/users-view.controller.js
> +                vm.currentUser = user;
Pourquoi t'as besoin de mettre à jour `vm.currentUser` ? Il y a que le mot de passe qui a changé et c'est pas quelque chose dont on se sert dans la page.
là du coup tu vas avoir oldPwd, newPwd1 et newPwd2 dans ton object `vm.currentUser` et je pense pas que ce soit voulu

2022-10-12 07:33 UTC, jajm commented on public/partials/users/users-modify-password-modal.html
> +                <div ng-if="vm.alertMessage && vm.alertMessage != ''" class="alert-block">{{ vm.alertMessage }}</div>
La classe `alert-block` fait que ça s'affiche en gris. Pas super visible pour un message d'erreur. Essaie plutôt les classes `alert alert-danger`
https://getbootstrap.com/docs/3.4/components/#alerts

Peut-être aussi le déplacer sous la checkbox ? Ça fait bizarre je trouve de l'avoir au milieu du formulaire

2022-10-12 07:33 UTC, jajm commented on public/js/users/users-view.controller.js
> +            });
Il faut aussi gérer le cas où la promesse est rejetée, sinon ça met un message d'erreur dans la console:
```
Possibly unhandled rejection: undefined
```

Une fonction vide suffit

2022-10-12 07:33 UTC, jajm commented on test/server/api/user.spec.js
> +            expect(res).toHaveProperty('status', 200);
Pour être complet, il manque juste un test qui vérifie que le mot de passe a bien été changé, par exemple en appelant User.isValidUserPassword

2022-10-13 09:35 UTC, ThibaudGLT commented on public/js/users/users-modify-password-modal.component.js
> +                notify.error(gettextCatalog.getString(error));
En effet c'est plus logique d'affecter l'erreur à vm.alertMessage

2022-10-13 09:41 UTC, ThibaudGLT commented on public/js/users/users-modify-password-modal.component.js
> +            vm.user = angular.copy(vm.resolve.user);
Je l'utilise dans le titre de la modale pour rappeler l'username en cours

2022-10-13 09:44 UTC, ThibaudGLT commented on public/js/users/users-modify-password-modal.component.js
> +        function showPasswords () {
yes

2022-10-13 09:44 UTC, ThibaudGLT commented on public/js/users/users-modify-password-modal.component.js
> +            const inputs = document.getElementsByClassName('input-passwd');
oui c'est vrai

2022-10-13 09:59 UTC, ThibaudGLT commented on public/js/users/users-view.controller.js
> +                vm.currentUser = user;
donc le mieux c'est de ne rien renvoyer ?

2022-10-13 10:00 UTC, ThibaudGLT commented on public/js/users/users-view.controller.js
> +                    user: () => vm.currentUser,
changé pour ne passer que l'username

2022-10-13 10:15 UTC, ThibaudGLT commented on public/partials/users/users-modify-password-modal.html
> +                <div ng-if="vm.alertMessage && vm.alertMessage != ''" class="alert-block">{{ vm.alertMessage }}</div>
J'ai adopté la classe css que tu m'as indiqué et j'ai déplacé le bandeau sous les boutons pour que ca évite de modifier la mise en page lorsqu'il y a une erreur, c'est une suggestion ;)

2022-10-13 12:30 UTC, jajm commented on public/js/users/users-modify-password-modal.component.js
> +            vm.user = angular.copy(vm.resolve.user);
Ah ok j'avais pas vu que le username était utilisé. Dans ce cas c'était ok, mais +1 pour passer uniquement le username ;)

2022-10-13 12:32 UTC, jajm commented on public/js/users/users-view.controller.js
> +                vm.currentUser = user;
Oui! :+1:

2022-10-13 12:44 UTC, jajm requested changes

2022-10-13 12:44 UTC, jajm commented on public/partials/users/users-modify-password-modal.html
> +        <div ng-if="vm.alertMessage && vm.alertMessage != ''" class="alert alert-danger">{{ vm.alertMessage }}</div>
Il faudrait juste le remonter d'un cran pour qu'il soit à l'intérieur du `.panel-body`

2022-10-13 12:44 UTC, jajm commented on public/js/users/users-modify-password-modal.component.js
> +            vm.username = angular.copy(vm.resolve.username);
pas besoin de angular.copy ici puisque vm.resolve.username est une string (copy est utile cloner un array ou un object et éviter de modifier l'object/array original; avec une string c'est déjà une copie qu'on a)

2022-10-13 12:44 UTC, jajm commented on public/js/users/users-modify-password-modal.component.js
> +                vm.close({ $value: vm.user });
`vm.user` n'existe plus. Tu peux faire `vm.close()` sans arguments je pense

2022-10-13 12:44 UTC, jajm commented on public/js/users/users-view.controller.js
> +            modal.result.then(() => {}).catch(() => {});
pas besoin du `.then` si tu fais rien dedans, contrairement au `.catch`

2022-10-13 13:20 UTC, jajm approved these changes

2022-10-14 12:12 UTC, merged